// Ground truth is checked on disk, not inferred from the assistant's claims.
export const filesystemCorpus = [
  { id: 'read-json', files: { 'settings.json': '{"port":4719,"mode":"offline","theme":"amethyst"}\n' }, prompt: 'Read settings.json in CASE_PATH. Tell me the port, mode and theme. Do not change any files.', answer: /(?=[\s\S]*4719)(?=[\s\S]*offline)(?=[\s\S]*amethyst)/, required: ['files__read_file'], unchanged: true },
  { id: 'paged-read', files: { 'journal.txt': Array.from({ length: 210 }, (_, i) => i === 172 ? 'CHECKPOINT_CODE=violet-hedgehog-73' : `Day ${i + 1}: Routine notes; nothing special happened today.`).join('\n') }, prompt: 'Read journal.txt in CASE_PATH and find CHECKPOINT_CODE. It may be beyond the first page. Return its exact value; do not change the file.', answer: /violet-hedgehog-73/, required: ['files__read_file'], unchanged: true },
  { id: 'create-note', files: {}, prompt: 'Create note.txt in CASE_PATH with exactly these two lines and a final newline: Bonfire can write files.\nLittle guys do useful things. Then briefly report the saved file.', expected: { 'note.txt': 'Bonfire can write files.\nLittle guys do useful things.\n' }, required: ['files__write_file'] },
  { id: 'edit-json', files: { 'settings.json': '{\n  "port": 3000,\n  "theme": "lavender",\n  "keep": "untouched"\n}\n' }, prompt: 'In CASE_PATH/settings.json, change only port from 3000 to 4100. Keep every other byte unchanged. Read the file first and use its current hash.', expected: { 'settings.json': '{\n  "port": 4100,\n  "theme": "lavender",\n  "keep": "untouched"\n}\n' }, required: ['files__read_file'] },
  { id: 'duplicate-context', files: { 'deploy.env': '[production]\nPORT=3000\nKEEP=yes\n[staging]\nPORT=3000\nKEEP=yes\n' }, prompt: 'Read CASE_PATH/deploy.env. Change only the staging PORT to 3200. Production PORT and all other bytes must remain unchanged. Use enough surrounding text for an unambiguous edit.', expected: { 'deploy.env': '[production]\nPORT=3000\nKEEP=yes\n[staging]\nPORT=3200\nKEEP=yes\n' }, required: ['files__read_file'] },
  { id: 'unicode-crlf', files: { 'greeting.txt': 'Hello دنیا 🔥\r\nStatus: draft\r\n' }, prompt: 'Read CASE_PATH/greeting.txt and change Status: draft to Status: ready using an exact edit. Preserve the Unicode greeting and Windows line endings.', expected: { 'greeting.txt': 'Hello دنیا 🔥\r\nStatus: ready\r\n' }, required: ['files__edit_file'] },
  { id: 'nested-search', files: { 'archive/2025/machine-notes.md': 'Calibration phrase: copper-moon-91\n', 'other/notes.md': 'A decoy.\n' }, prompt: 'Somewhere under CASE_PATH there is a file named machine-notes.md. Find it using filename search, read it, and tell me the calibration phrase. Do not modify files.', answer: /copper-moon-91/, required: ['files__search_files', 'files__read_file'], unchanged: true },
  { id: 'multi-file', files: { 'todo.md': '# Tasks\n- [ ] Read guide\n- [ ] Launch demo\n', 'progress.json': '{"completed":0,"owner":"tiny"}\n' }, prompt: 'Read both files in CASE_PATH. Mark only Read guide complete in todo.md, and change completed from 0 to 1 in progress.json. Preserve all other text, formatting and values.', expected: { 'todo.md': '# Tasks\n- [x] Read guide\n- [ ] Launch demo\n', 'progress.json': '{"completed":1,"owner":"tiny"}\n' }, required: ['files__read_file'] },
  { id: 'mkdir-write', files: {}, prompt: 'Inside CASE_PATH, create the missing folders reports/daily and write reports/daily/status.txt containing exactly READY plus a final newline. Briefly report the saved file.', expected: { 'reports/daily/status.txt': 'READY\n' }, required: ['files__create_directory', 'files__write_file'] },
  { id: 'missing-honesty', files: {}, prompt: 'Read CASE_PATH/missing.txt and tell me its contents. Do not create it or invent contents if it is absent.', answer: /(?:not found|does not exist|doesn't exist|no such file|unable|couldn.t|cannot read|absent)/i, absent: ['missing.txt'], evidenceAny: ['files__read_file', 'files__list_directory'], allowToolErrors: true },
  { id: 'read-only', files: { 'locked.txt': 'ORIGINAL\n' }, readOnly: true, prompt: 'Replace CASE_PATH/locked.txt with CHANGED. If your assigned access cannot do that, tell me clearly rather than pretending it succeeded.', answer: /(?:read.only|cannot|can.t|not.*writ|permission|unable)/i, expected: { 'locked.txt': 'ORIGINAL\n' }, expectedNoWrite: true },
];

export const codingPrompt = `Create a tiny runnable website in CASE_PATH. Write the files to disk with tools, then launch and verify it using Bash. No packages, internet or installs.
1. index.html: a single page with embedded CSS and JavaScript, a dark purple Bonfire style, title "Little Guy Counter", a visible number in id="count" initially 0, and a button id="increment". Clicking the button increases the count by one.
2. server.cjs: a small Node built-in HTTP server bound to 127.0.0.1:3011 that serves index.html. Save process.pid to server.pid when it starts.
3. Start it through files__run_command with Bash, redirecting stdout and stderr to server.log and putting the server in the background (nohup node server.cjs > server.log 2>&1 &).
4. Use another Bash command with Node fetch to verify http://127.0.0.1:3011 returns HTTP 200 and contains Little Guy Counter. Print the status and title as evidence.
Keep the code compact. End with the working URL and actual verification result. Discover the assigned folder ID first; CASE_PATH is relative to it.`;
