import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const directory=path.join(root,'results');
const files=process.argv.slice(2);
if(!files.length && fs.existsSync(directory)) files.push(...fs.readdirSync(directory).filter(f=>f.endsWith('.json')).map(f=>path.join(directory,f)));
if(!files.length) throw new Error('No runs yet. Run the bake-off first; see bench/README.md.');
const runs=files.map(file=>({file,...JSON.parse(fs.readFileSync(file,'utf8'))}));
if(runs.some(r=>!['bonfire-tools-v1','bonfire-tools-v1.1'].includes(r.suite))) throw new Error('Unknown benchmark suite.');
if(new Set(runs.map(r=>r.suite)).size!==1) throw new Error('Compare only runs of the same fixture revision.');
fs.mkdirSync(directory,{recursive:true});
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const percentile=(xs,p)=>xs.length?[...xs].sort((a,b)=>a-b)[Math.ceil(xs.length*p)-1]:0;
const pct=(n,d)=>d?`${(100*n/d).toFixed(1)}%`:'—';
const stats=r=>{
 const calls=r.results.flatMap(c=>c.trace);
 const passed=r.results.filter(c=>c.pass).length;
 const timings=r.results.flatMap(c=>c.turns).map(t=>t.timings).filter(t=>t?.predicted_ms>0);
 const decode=timings.length?1000*timings.reduce((n,t)=>n+t.predicted_n,0)/timings.reduce((n,t)=>n+t.predicted_ms,0):null;
 return {passed,total:r.results.length,score:pct(passed,r.results.length),schema:pct(calls.filter(c=>c.valid).length,calls.length),writes:r.results.reduce((sum,c)=>sum+c.failures.filter(f=>f.startsWith('Unauthorized write attempted:')).length,0),p50:percentile(r.results.map(c=>c.elapsedMs),.5)/1000,p95:percentile(r.results.map(c=>c.elapsedMs),.95)/1000,decode,errors:r.results.filter(c=>c.error && c.errorKind!=='budget' && !/safety limit reached/.test(c.error)).length};
};
const head=['Model / run','Task success','Valid tool arguments','Unauthorized write attempts','Median task','p95 task','Decode tok/s','Server errors'];
const rows=runs.map(r=>{const s=stats(r);return [r.label+(r.settings.chat_template_kwargs.enable_thinking?' (thinking)':' (no thinking)')+(r.summary?.complete?'':' · INCOMPLETE'),`${s.passed}/${s.total} · ${s.score}`,s.schema,s.writes,`${s.p50.toFixed(1)}s`,`${s.p95.toFixed(1)}s`,s.decode?.toFixed(1)||'—',s.errors];});
const auditReasons=[...new Set(runs.map(r=>r.audit?.reason).filter(Boolean))];
const hardware=runs.find(r=>r.hardware)?.hardware;
const context=`<p>Suite: ${escape(runs[0].suite)}. ${hardware?escape(`${hardware.gpu}, ${hardware.vramMiB} MiB VRAM · ${hardware.cpu} · ${hardware.ramMiB} MiB RAM · ${hardware.backend}`):'Hardware metadata is in server logs.'} 8,192-token context; temperature 0.1; seed 42. Repetitions: ${runs.map(r=>`${escape(r.profile)} ${r.settings.chat_template_kwargs.enable_thinking?'thinking':'no thinking'} × ${r.repeat}`).join('; ')}.</p><p>Median/p95 cover all attempted tasks, including early failures. Decode throughput excludes prompt processing and is not the same as task completion speed. llama.cpp grammar constraints helped all models emit valid argument JSON.</p>${auditReasons.length?`<h2>Fixture audit</h2>${auditReasons.map(reason=>`<p>${escape(reason)}</p>`).join('')}`:''}`;
const ids=[...new Set(runs.flatMap(r=>r.results.map(c=>c.id)))];
const matrix=ids.map(id=>[id,...runs.map(r=>{const cs=r.results.filter(c=>c.id===id);return cs.length?`${cs.filter(c=>c.pass).length}/${cs.length} · ${(percentile(cs.map(c=>c.elapsedMs),.5)/1000).toFixed(1)}s`:'Not run';})]);
const table=(headers,body)=>`<table><thead><tr>${headers.map(h=>`<th>${escape(h)}</th>`).join('')}</tr></thead><tbody>${body.map(row=>`<tr>${row.map(v=>`<td>${escape(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
const details=runs.map(r=>`<section><h2>${escape(r.label)}</h2><p>${escape(r.startedAt)} · ${escape(r.file)}${r.completedAt?'':' · INCOMPLETE RUN'}</p>${r.results.map(c=>`<details><summary class="${c.pass?'pass':'fail'}">${c.pass?'PASS':'FAIL'} ${escape(c.id)} · ${(c.elapsedMs/1000).toFixed(1)}s</summary><p>${escape(c.prompt)}</p><p>${escape(c.failures.join('; '))}</p><h3>Final answer</h3><pre>${escape(c.answer)}</pre><h3>Tool trace</h3><pre>${escape(JSON.stringify(c.trace,null,2))}</pre></details>`).join('')}</section>`).join('');
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Bonfire tool bake-off</title><style>body{font:15px system-ui;background:#11151a;color:#e4e9ef;max-width:1200px;margin:32px auto;padding:0 20px}h1{color:#ffad6c}table{border-collapse:collapse;width:100%;margin:20px 0}td,th{padding:12px;border-bottom:1px solid #35414b;text-align:left}th{background:#1d252d}details{margin:10px 0;background:#1d252d;padding:12px;border-radius:6px}summary{cursor:pointer}.pass{color:#82dfae}.fail{color:#ff9696}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#11151a;padding:12px}p{line-height:1.6;color:#bfc9d3}.scroll{overflow-x:auto}</style><h1>Bonfire · tool calling bake-off</h1><p>Deterministic local fixtures · structured calls · no real writes or web search. A task passes only when the required calls, dependency order, arguments, boundaries, and final answer checks all pass.</p><div class="scroll">${table(head,rows)}</div><h2>Case comparison</h2><div class="scroll">${table(['Case',...runs.map(r=>r.label)],matrix)}</div><p>Compare complete runs of the same cases and thinking settings. Schema success can benefit from llama.cpp grammar constraints; task success is the main metric. First-call timing and token counts are in each JSON. These are small diagnostic cases, not a general intelligence ranking. Regex answer checks need human review for false positives and false negatives. Report contains no LLM judge.</p>${details}</html>`;
fs.writeFileSync(path.join(directory,'comparison.html'),html.replace('<h2>Case comparison</h2>',context+'<h2>Case comparison</h2>'));
const markdown=`# Bonfire tool bake-off\n\n| ${head.join(' | ')} |\n| ${head.map(()=>'---').join(' | ')} |\n${rows.map(row=>'| '+row.map(v=>String(v).replace(/\|/g,'\\|')).join(' | ')+' |').join('\n')}\n\nOpen comparison.html for per-case results and tool traces. Review answer checks manually before picking a model.\n`;
fs.writeFileSync(path.join(directory,'comparison.md'),markdown);
console.log(`Wrote ${path.join(directory,'comparison.html')} and comparison.md`);
